"""criando book table

Revision ID: 2a93660ae428
Revises: bf00a3ee7a1b
Create Date: 2025-09-12 15:59:05.113808

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2a93660ae428"
down_revision: Union[str, Sequence[str], None] = "bf00a3ee7a1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
