name: Deploy
on:
  push:
    branches: 
      - 'main'
      - 'feature/**'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl "${DEPLOY_URL}&ref=${COMMIT_SHA}"
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          COMMIT_SHA: ${{ github.sha }}
