name: Build - Tests and Coverage using uv

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: uv setup
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: uv sync
        run: uv sync --locked --all-extras --dev

      - name: run tests and generate html artifact 
        run: uv run pytest --cov=src --cov-report=html:html

      - name: upload html coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: html/
          retention-days: 7
